### PR TITLE
Update config.yaml to Support Addons Config

### PR DESCRIPTION
**Pull request by linickx**
# Proposed Changes

Update `config.yaml` map to include all add-on configs so that databases which are stored there can be opened.

## Related

* https://developers.home-assistant.io/blog/2023/11/06/public-addon-config/

## Summary by CodeRabbit

- **New Features**
  - Added support for managing all add-on configurations with read and write permissions.

### CODE REVIEW

**Comment by frenck** [comment]
I consider this quite a thing, as giving unneeded access IMHO, is something to avoid (considering security). Could you provide a concrete and common use case that would justify this change? The motivation for this is currently not provided in the PR description.

../Frenck

**Comment by linickx** [comment]
The blog post referenced encourages the use of public add-on config directory instead of _config_ to improve security. 

Any developers looking to enhance their security my migrating their add-on SQLLite Db's out of config into the safer add-on config directory cannot use this add-on and need to roll their own solution.

The concern about expanding footprint does make sense, but of course this add-on already has access to secrets/etc stored in config. The assumption I have made is that addons_config is a lower security risk than homeassistant config, of course I understand that could be wrong.

**Comment by frenck** [comment]
> The blog post referenced encourages the use of public add-on config directory instead of config to improve security.

Sure, but for this add-on specifically its goal is to access the Home Assistant database... so that isn't related to this PR at all.

> Any developers looking to enhance their security by migrating their add-on SQLLite Db's out of config into the safer add-on config directory cannot use this add-on and need to roll their own solution.

That is cool, but not a concrete example.

> The concern about expanding footprint does make sense, but of course this add-on already has access to secrets/etc stored in config. The assumption I have made is that addons_config is a lower security risk than homeassistant config, of course I understand that could be wrong.

They are not related at all, I'm failing to understand this reasoning. Probably because the lack of concrete examples is missing.

../Frenck

**Comment by linickx** [comment]
Thanks for your feedback. 

> this add-on specifically its goal is to access the Home Assistant database

I understand, happy to close/cancel the PR.

**Pull request closed without merging**
